name: wasab
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  logger: ^2.3.0
  shared_preferences: ^2.2.3
  dio: ^5.4.3+1
  easy_localization: ^3.0.7
  get_it: ^7.7.0
  pin_code_fields: ^8.0.1
  flutter_svg: ^2.0.10+1
  flutter_staggered_animations: ^1.1.1
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/svg/
    - assets/images/icons/
    - assets/images/gif/
    - assets/languages/

  fonts:
    - family: font_regular
      fonts:
        - asset: assets/fonts/font_regular.ttf
    - family: font_bold
      fonts:
        - asset: assets/fonts/font_bold.ttf